### ISSUE TITLE
Sea ice concentration map difference doesn't goto -1,1

### ISSUE THREAD

**Issue by akturner** [MPAS-Dev/MPAS-Analysis#250]
The difference maps for the standard climatology for sea ice concentration have a range of +-80% rather than +-100%. This leaves white regions in the middle of regions where the model is most different from observations. Would it be possible to change this to +-100%?

**Comment by milenaveneziani** [comment]
or, we could add the colors for the values above the maximum and below the minimum (with little triangles), which is something that I've been wanting to do for a while..

**Comment by akturner** [comment]
Was there a reason 80-100% was left out though?

**Comment by milenaveneziani** [comment]
no, no particular reason. I was only bounded by the number of color levels. So, if we add two color levels, we can go -100 to 100 and keep the rest the same.
Adding two levels would help the thickness bias plots as well, because also in that case there are white spots for when the bias>3m, or whatever is the max colorbar level.

**Comment by xylar** [comment]
@milenaveneziani, I'm assuming this is something you can take care of?  It sounds like a pretty simple fix. 
 I'm happy to review.

**Comment by xylar** [comment]
Addressed by #255
