### ISSUE TITLE
Application to high res data generates too many warnings

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Analysis#268]
Not sure if this is the right place for this issue as it is NCO related, but I have been trying to run MPAS-Analysis on the high res simulation being run on anvil and I get a ton of the same warning
```
WARNING: nco_close() reports variable timeMonthly_avg_normalVelocity is "large" (7126817280 B =~ 6 GiB > 4294967296 B = 4 GiB)
WARNING: nco_close() reports variable timeMonthly_avg_normalTransportVelocity is "large" (7126817280 B =~ 6 GiB > 4294967296 B = 4 GiB)
WARNING: nco_close() reports total number of "large" (> 4 GiB) variables in this CDF5 file is 2
WARNING: nco_close() reports at least one "large" (> 4 GiB) variable in this CDF5 file is not the last variable defined. Writing CDF5 files with large variables is buggy in netCDF library versions 4.4.0-4.4.1 unless there is only one such "large" variable and it is the last to be defined. Input datasets (that NCO reads) that were originally written by PnetCDF are likely fine (because PnetCDF writes CDF5 through a different mechanism than serial programs like NCO's writer). And CDF5 datasets originally written by any netCDF version 4.5.0 or greater are likely fine. However, input files written by any serial netCDF writer (like NCO) employing netCDF library 4.4.x are likely corrupt and variables were silently truncated when writing it. An output file (that this NCO _writes_) will definitely be corrupt, as this NCO employs (i.e., is linked to) netCDF library version 441 which is buggy (so please upgrade to netCDF 4.5.x ASAP).
HINT: There are two potential solutions for data affected by this bug: 1. Re-write (using any netCDF version) original input files in netCDF4 format instead of CDF5, then process these as normal and write netCDF4 output (instead of CDF5); 2. Re-compile NCO with netCDF library 4.5.0 or later and use it to convert non-corrupt datasets to netCDF4 format, then process the data. This message should only appear if there is a possibility that you are reading or writing a corrupt dataset. Sorry to scare you if this is a false positive. For more information on this nasty bug, see https://github.com/Unidata/netcdf-c/issues/463
INFO: nco_close() currently closing and sniffing-around for corruption in CDF5 file /lcrc/group/acme/lvanroe/case_output/test_20171021.tune.GMPAS-IAF.T62_oRRS18v3.anvil/clim/mpas/timeMonthly_avg_dThreshMLD_oRRS18to6v3/mpaso_08_000608_000608_climo.nc
Climatological monthly mean for month 9 ...
INFO: nco_close() currently closing and sniffing-around for corruption in CDF5 file /lcrc/group/acme/lvanroe/acme_scratch/20171021.tune.GMPAS-IAF.T62_oRRS18v3.anvil/run/./mpaso.hist.am.timeSeriesStatsMonthly.0006-09-01.nc
```
I certainly see the value of this warning, but it would be nice if it didn't happen every single time (or have an option to supress completely) a NCO operation is performed.  It is impossible to see what analysis is being run.  Pinging @czender

**Comment by czender** [comment]
Yes, I can see how that would be nice. High-res MPAS is the only known application where users regularly encounter the CDF5 bug. I added those warnings in 4.6.9 to alert mainly other people to the bug (few except MPAS and netCDF developers are aware of it). The only way (sorry) to turn it off in 4.6.9 is to redirect stdout to /dev/null.  
In 4.7.0, to be released real soon now, I modified the warning but it will still be loud and annoying for files with the CDF5 bug, i.e., for you MPAS folk. It's difficult to turn-off at run-time because of where it is in the NCO library. Making it a run-time quiet-able WARNING could be done, though it would delay 4.7.0 by possibly a few weeks. I could easily disable the WARNING completely in 4.7.0 since it has not been released yet. What do MPAS folk want done?

**Comment by xylar** [comment]
@vanroekel, I assume this must mean you're running MPAS-Analysis in serial mode (maxParallelTasks=1).  If you run in parallel mode, each task's output will be directed to a separate log file, which would hopefully make it easier to figure things out.  Even so, I think you're going to have to deal with the verbose output for the time being.  I'll defer to you on what you'd like to see in NCO 4.7.0, since you're the one most affected for now.

**Comment by vanroekel** [comment]
correct this was serial.  I can certainly flip to parallel.  If there are no objections from others, I would prefer to disable the warning for NCO 4.7.0.  If I recall correctly this error only applies to doing the high-res MOC post process, which we won't be doing now.

**Comment by czender** [comment]
NCO 4.7.0 has been released. Once it is turned into a conda package and integrated into MPAS analysis the annoyingly verbose CDF5 warnings for the MOC files should disappear.

**Comment by xylar** [comment]
Thanks, @czender.  I have just made a pull request to update the NCO recipe on conda-forge:
https://github.com/conda-forge/nco-feedstock/pull/47

Hopefully it will be merged in the next day or 2.  I'm not sure how soon I'll be able to update acme-unified but shouldn't be *too* long.

**Comment by xylar** [comment]
Addressed in latest NCO, which will be included in next e3sm-unified environment.
