### ISSUE TITLE
Calculation of datetime to be unified in the future 

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#33]
Eventually, the timeSeriesStats AM for both ocean and ice will have xtime_start and xtime_end in their output files. For now, this is only true for MPAS-O, which is the reason why there is logical branching via https://github.com/pwolfram/mpas_xarray/blob/master/mpas_xarray/mpas_xarray.py#L105 to modify daysSinceStartOfSim.

cc @milenaveneziani

**Comment by xylar** [comment]
I have a solution to this issue in the following branch:
https://github.com/xylar/MPAS-Analysis/tree/fix_time_series_subset

I would like to also address #45 (allowing time-series analysis over a subset of the data) in this branch before making a PR unless there are objections.  As @pwolfram pointed out, the two issues are related, which is why I ended up needing to solve this issue before I could get to #45.

**Comment by xylar** [comment]
By the way, I think the default start date used to compute dates using some variant on `daysSinceStartOfSim` is incorrect:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/shared/mpas_xarray/mpas_xarray.py#L123
If you start from 12/31/1849 and add `daysSinceStartOfSim`, you only end up at 01/01/1850 (which *should* be the start date) after one day of simulation (`daysSinceStartOfSim = 1`):
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/shared/mpas_xarray/mpas_xarray.py#L165

I think this is a bug and I have fixed it in the branch above by using 01/01/1850 as the reference date.

**Comment by xylar** [comment]
I changed my mind and did a PR (#46) specifically for the bug mentioned above since it's a non-bit-for-bit change.  I'll probably also submit a separate fix for this issue and for #45 because that, too, will be cleaner.

**Comment by pwolfram** [comment]
@xylar, is there anything outstanding on this issue?  Otherwise, I think we can close it.

**Comment by xylar** [comment]
Addressed by #47.
