### ISSUE TITLE
develop branch

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#39]
I went ahead and created a `develop` branch and made it the default for this repo.  However, this deserves discussion and buy-in from everyone involved in this repo.  This issue page is meant to allow us to discuss any cons and to make sure everyone knows what changes were made and why.

**Comment by xylar** [comment]
The `develop` branch has been created to allow us to merge development without affecting the [PreAndPostProcessingScripts](https://github.com/ACME-Climate/PreAndPostProcessingScripts) repo.  The idea is that changes are only merged to master after they have been confirmed to do no harm in ACME.

**Comment by xylar** [comment]
@pwolfram raised concerns in https://github.com/MPAS-Dev/MPAS-Analysis/pull/29#issuecomment-256524567 that this decision was made unilaterally without time for group discussion.  I definitely understand the concerns.  As I have said in #29, I felt that 1) the changes could easily be undone if desired and 2) a merge to master that broke ACME could *not* be undone quite as easily.  So I decided to go ahead and add a develop branch.

So let's have a retroactive discussion about whether we think that was a good plan, and also about what best practices should be for such changes in the future.

**Comment by pwolfram** [comment]
@xylar, I agree with you that this is the right decision.  Thanks for the forward thinking that will probably save us a fair amount of the time in the future.  My comment was mainly regarding the culture we are building and I really appreciate you opening this issue because I just want to make sure that we haven't missed a key viewpoint that another person may raise.  

Full disclaimer: I just realized I merged #29 into develop prematurely but am happy to merge the code into the correct location if we decide against develop.  Building personal habits toward the proper culture is a work in progress for me too.

@milenaveneziani and @vanroekel, do you see any problems with using a develop branch to better buffer the code against spurious merges and help coordinate merging to ACME?  

If not I recommend we continue from this point forward using develop and close this issue.

**Comment by vanroekel** [comment]
I think a develop branch is the right idea.  If I understand correctly with develop we wouldn't inadvertently break the acme portion of the analysis.  And develop could be used for testing integration of new testing into acme.  Seems like a really great idea to continue with develop.

**Comment by pwolfram** [comment]
Since no one has raised objections the plan is to use the develop branch and close this issue.  Please reopen if you disagree.
