### ISSUE TITLE
Use of "refField*" for both observations and reference runs is confusing

### ISSUE THREAD

**Issue by bradyrx** [MPAS-Dev/MPAS-Analysis#424]
In analysis subtasks (and subsequently plotting subtasks), it is confusing that the variable `refFieldName` and `refTitleLabel` is used for both reference runs and observations. It would seem that it should only be applied to the former, given `refConfig` is used for configuration options for a reference run.

**Comment by xylar** [comment]
@bradyrx, thanks for posting this.  I need to think of what a better name would be for the "other" plot besides the "main" model result and the difference.  @milenaveneziani, any thoughts?

**Comment by milenaveneziani** [comment]
I can't think of a better general name either. How about we change the name of `refConfig`, something like `refRunConfig` vs `mainRunConfig`?

**Comment by xylar** [comment]
@milenaveneziani, I have a branch where I changed "ref" to "control" in cases where "ref" refers to either observations or a reference run.  I could do the opposite, that is, change "ref" to "control" when referring to a control run, but leave "ref" in cases where we're talking about either observations or a control run.  Which would you find more intuitive?

**Comment by milenaveneziani** [comment]
So, mainRun=control, refConfig=either refRun or observations. But this is pretty much as it is now, right? To me, this isn't confusing..

**Comment by xylar** [comment]
No, the way we do plotting, the reference run would be the control run.  That's because of how we do the bias or difference plot.  If you want to look at the anomaly based on some change you've made, that's the modified run minus the control run.  So the "reference" run is the control run.

I think this had @darincomeau confused for awhile, too.  So maybe if I change "reference" run to control run but leave "ref" to mean either the control run or the observations, that'll be more intuitive?
