### ISSUE TITLE
Analysis linked to publicly available observational datasets

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#5]
Observational data should be observational datasets, potentially stored in a separate repository (to keep analysis script repositories light-weight).  For example, we could keep them in a centralized location where data that is need is downloaded and cached locally.  
- [ ] Keep track of hash sum verification that files are the same.  
- [ ] Want this resource to be publicly available (could be https://git-lfs.github.com/ or http://data.kitware.com/ or something else).
- [ ] Only pull in necessary data / provide soft links to data as possible.

**Comment by pwolfram** [comment]
@milenaveneziani, my understanding is that we are currently self-managing this process by pointing to a folder where these datasets have been copied on the local machine.  If we could get them on a server somewhere we could have them automatically downloaded if a particular file is missing.  This would make the analysis capability more robust.  Ultimately, I think this is what we want but moving forward on this is obviously a question of priority.  

Note, I don't think we have a way to verify that the observational datasets haven't been corrupted (first check box above), e.g., we aren't storing a file hash for them to verify they are as the analysis system expects.  Is this also the case?

**Comment by xylar** [comment]
I think this may end up being a somewhat bigger project than just putting the existing observations on a server.   Maybe your appreciate that already.

The current analysis capabilities are heavily weighted toward what ACME v1 needs right now (which is fine as far as it goes) but we really want a more general capability that applies to MPAS simulations generally and not just to the needs of ACME v1.  I guess I just want to make sure that this issue is addressed in a modular way that can easily be broadened to include new observations from other sources as new analysis capabilities are added.

**Comment by milenaveneziani** [comment]
I agree, this is a big project, and was thinking to dedicate a full Epic to it on Jira (2017 roadmap).

**Comment by pwolfram** [comment]
Note, this is related to #17 and the design solution here should optimally be general enough to cover the broader issue #17.

**Comment by xylar** [comment]
@pwolfram, if you're suggesting we close this issue and stick with #17, that's fine with me.

**Comment by pwolfram** [comment]
Thanks @xylar, I'm closing this issue and migrating the checkboxes to #17 for simplicity.
