### ISSUE TITLE
Timeseries data go from Jan of yr1 to Jan of yr2+1, instead of Dec of yr2

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#60]
1. When specifying a yr1 and a yr2 for the timeseries plots, the data loaded go through Jan of yr2+1, instead of Dec of yr2.

2. As an aside, a similar thing happens for climo_yr1 and climo_y2 (data goes from Dec of climo_yr1-1 through Jan of climo_yr2+2), but perhaps this was done on purpose to compute proper seasonal climatologies for DJM? we should look into this too.

**Comment by xylar** [comment]
@milenaveneziani, could you clarify both issues, but particularly the second one?  The files for one month before and one month after the given range are loaded on purpose, just in case.  This means that you will see on stdout that the files were loaded.  But that doesn't necessarily mean they are used by xarray in computing the climatology.  Do you know from something other than the list of files used that the climatology is being computed from the wrong range of data?

The same could be true for the first issue.  Are the plots themselves showing too much data, or just the list of files being accessed?

Remember that we decided it was safest to add a buffer around either side of the date given in the file because we don't know for sure if the date accurately reflects the beginning or end (or something else like the middle?) of the dates contained in the file.

**Comment by milenaveneziani** [comment]
I now remember what we decided for climo_yr1 and climo_yr2, @xylar, sorry for forgetting. I am pretty sure the climos are computed correctly. The reason I noticed is that I wanted to compute a climatology for years 71-100 from beta0 results, and Jan of year 101 has permission problems, so I had to use 71-99. But this is a different problem.

And I re-checked what I was getting for timeseries_yr1 and yr2, and it seems that a similar reasoning was used there too.
So, I am closing this issue, if it is OK with you too.

**Comment by xylar** [comment]
Yes, I think it's just confusion with file names.

Regarding your permission problem, that might be something to put in as an issue.  It might be best if the code gives a warning (but moves on) if it doesn't have permission to read a given file.
