### ISSUE TITLE
WOA18 seems to have the same data for all seasons

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#634]
These 3 images should have different obs but have seemingly the same:
[ANN](https://portal.nersc.gov/project/m2833/mpas_analysis_output/woa18_TS/20190405.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta/yrs11-20/ocean/temperatureWOA18_antarctic_20190405.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta_depth_top_ANN_years0011-0020.png)
[JFM](https://portal.nersc.gov/project/m2833/mpas_analysis_output/woa18_TS/20190405.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta/yrs11-20/ocean/temperatureWOA18_antarctic_20190405.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta_depth_top_JFM_years0011-0020.png)
[JAS](https://portal.nersc.gov/project/m2833/mpas_analysis_output/woa18_TS/20190405.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta/yrs11-20/ocean/temperatureWOA18_antarctic_20190405.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta_depth_top_JAS_years0011-0020.png)

**Comment by xylar** [comment]
@milenaveneziani, could you look into this if you get a chance?  I'll try as well when I get time.  Something isn't working quite as expected, I think.

**Comment by milenaveneziani** [comment]
I see the problem now. Wow: great job spotting this!
I will look into it.

**Comment by milenaveneziani** [comment]
@xylar: I believe all seasons are using the annual climatology file. Not sure why that is the case though.

I wish I knew how to point to specific files in here, but basically, in `mpas_analysis/shared/climatology/remap_observed_climatology_subtask.py`, line 147:
```
        obsFileName = self.get_file_name(stage='original')
```
the `obsFileName` points either to `clim/obs/t_anWOA18_0.25x0.25degree.nc` or to `clim/obs/s_anWOA18_0.25x0.25degree.nc` as it *should* be, but when you look at those files they are *always* the annual averages. They are not the annual averages when season=ANN and the monthly climatologies when season is different from ANN. So something goes wrong when going from the original obs files:
```
woa18_decav_04_TS_ann_20190829.nc 
woa18_decav_04_TS_mon_20190829.nc
```
to the files in `clim/obs` mentioned above.

Note that we did not have this problem with ARGO because in that case we are only using the monthly climatologies (and ANN is computed from the monthly fields), while for WOA I wanted to use the original `ann` file.

Does it make sense?

**Comment by milenaveneziani** [comment]
One more thing: when I print `obsFileName` right after this:
```
                    if season == 'ANN':
                        obsFileName = \
                            '{}/woa18_decav_04_TS_ann_20190829.nc'.format(
                                observationsDirectory)
                    else:
                        obsFileName = \
                            '{}/woa18_decav_04_TS_mon_20190829.nc'.format(
                                observationsDirectory)
```
in `mpas_analysis/ocean/climatology_map_woa.py`, I get the right filename according to the season, i.e. I get the `woa18_decav_04_TS_ann_20190829.nc` file when season=ANN and the `woa18_decav_04_TS_mon_20190829.nc` file when season is different from ANN.

so clearly something goes wrong when `RemapWoaClimatology` is invoked.

**Comment by xylar** [comment]
@milenaveneziani, I will look into this right now but I think what's going on is that both the monthly and the annual climatologies get written to the same files:
```
clim/obs/t_anWOA18_0.25x0.25degree.n
clim/obs/s_anWOA18_0.25x0.25degree.n
```
Which one "survives" and which gets lost is a question of the order in which the tasks run, and indeed we would expect crashes sometimes when they run simultaneously, so that's a problem!

If I'm right about that, the fix would simply to be to have different output file names for the two.  I don't think that will be too hard to arrange.

**Comment by milenaveneziani** [comment]
yes, that is exactly what I think it is happening. I can see they are the annual climatology file, not he 12-monthly file, which is why I think what we see in the plots is always the annual climo.
I tried to find where exactly these files are written to `clim/obs`, but wasn't able to.

**Comment by xylar** [comment]
The fix is slightly more complicated than I thought.  We are currently remapping observations once per season and per field (T and S), whereas we really only want to be remapping once per field and once each for annual and monthly.  I'm testing a fix right now.
