### ISSUE TITLE
Likely bug in computing time series for 2-d variables

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#636]
I have been running an 'extracted' (outside the MPAS-Analysis framework) version of the `time_series_ocean_regions.py` task, making regional time series plots for a variety of variables, including 2-d freshwater flux variables, and 3 main depth ranges (0-50m, 400-1000m, and 1000-4000m). 
When choosing 2-d variables I ran into a couple of problems, listed below (1. is the main problem).

As reference, this is the script I am using:
https://gist.github.com/milenaveneziani/da0af2e2b4db75e922a70362f517720a

Changes from the original version include:
1) Lines 244-245 of the gist has the correct computation of the regional average for 2d variables:
```
                            (dsRegion.areaCell*timeSeries).sum(
                                dim='nCells') / totalArea
```
this is because both `dsRegion` and `timeseries` are *already* regional quantities, so no need to multiply times the `cellMask`.

2) the addition of a 'is3d' entry for the `variables` dictionary. This was needed for me because, if I am just reading information from previously computed time series, I loose the bit of info related to 3d or 2d variables (and I will need that during the plotting part, to define an appropriate title and output figure filename). Perhaps this is not needed in the MPAS-Analysis version;

3) see lines 307-321 of the gist for changes related to defining a better title/fig filename according to 3d or 2d variables. 

Thought I'd document this here, so that we can take it into account for the MPAS-Analysis task.

**Comment by xylar** [comment]
@milenaveneziani, sorry for not getting to this sooner.

Regarding 1), it never occurred to me to support 2D variables, to be honest, but I see that there's no reason it couldn't be supported as you have done. 

Regarding 2), I think you could just add 'is3d' to the dictionary based on whether the variable has `nVertLevels` as a dimension (when you're computing the regional mean at each time index) and then read back from the dictionary later on.

Regarding 3) Yep, again, an easy modification to make, following your gist, once we've stored 'in3d' as I suggest in 2).

 If you want to make a PR, that's great.  Otherwise, I'll get to it when I can.

**Comment by milenaveneziani** [comment]
> Regarding 1), it never occurred to me to support 2D variables, to be honest, but I see that there's no reason it couldn't be supported as you have done.

well, you did add this if statement here though:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/4dff0fcfa06f2e276f3c3ad1e4b5fd227338de7f/mpas_analysis/ocean/time_series_ocean_regions.py#L436

so I assumed you meant to include this case as well.

In any case, yes, this would be easy to implement, and useful 'cause we could use it for looking at the surface fluxes (which is what I am doing now).

**Comment by xylar** [comment]
Ah, I guess I did and I just forgot.

**Comment by xylar** [comment]
This should be quite fast to fix.  I'll work on it now, actually.
