### ISSUE TITLE
Fixed plot size for easier comparison

### ISSUE THREAD

**Issue by golaz** [MPAS-Dev/MPAS-Analysis#765]
When I compare multiple simulations, I will often open several tabs in my browser and then quickly switch back and forth to visualize differences between the figures. Unfortunately, this often doesn't work very well because figures do not necessarily have the same size (due to varying title length).

For example, try opening the following two pages in separate tabs and then switching back and forth:

https://compy-dtn.pnl.gov/gola749/E3SM/v2/beta/20201211.beta1_01.piControl.compy/mpas_analysis/ts_0001-0100_climo_0071-0100/ocean/index.html#global_mld&gid=1&pid=2

https://compy-dtn.pnl.gov/zhen797/alpha5/mpas_analysis/alpha5_59.fallback_piCtl/ts_0001-0100_climo_0051-0100/ocean/index.html#global_mld&gid=1&pid=2

to get around this problem, I would suggest considering using fixed size instead.

**Comment by xylar** [comment]
@golaz, this is a great suggestion, something that we have also found annoying.

It is hard to know ahead of time what the size of the figure is to fix the size, since the same code generates hundreds of slightly different figures.  As far as I am aware, the cause of the different figure size is always the different lengths of very long run names.

Would truncating the run name to a maximum allowed length in these titles be an acceptable solution to you?  @milenaveneziani, is that okay with you as well?

I should be able to take care of this over the weekend and include it in the v1.3.0 release to be included in the E3SM-Unified release on Jan 1st.

**Comment by milenaveneziani** [comment]
yes, my solution to this has been to use a shortened version of the runname.

I think the truncation would work, although maybe it would be nice for the user to know right away whether the chosen name is too long, with a warning or something.

**Comment by xylar** [comment]
@milenaveneziani, I agree, it might be good to warn the user that the name of the run will be shortened in a lot of plots.

**Comment by golaz** [comment]
@xylar, thanks so much for working on this. Yes, shortening long titles should take care of it.
