### ISSUE TITLE
Add quantitative metrics to lat-lon plots

### ISSUE THREAD

**Issue by golaz** [MPAS-Dev/MPAS-Analysis#767]
It would be useful to add some quantitative basic metrics to MPAS-Analysis lat-lon plots, such as for example:

- global mean (for model, obs)
- mean biais (for difference)
- RMSE  (for difference)
- correlation (for difference)

**Comment by xylar** [comment]
@golaz, another really good suggestion.  I think @milenaveneziani had also mentioned wanting to add these but obviously it slipped through the cracks.

As with the others, I should be able to take care of this over the weekend and include it in the v1.3.0 release to be included in the E3SM-Unified release on Jan 1st.

**Comment by milenaveneziani** [comment]
I have added the mean and rsme values to the bias plots already.
The global means for the model and obs panels can be added as easily.

@golaz: what do you mean by 'correlation'? how do you calculate it?

**Comment by xylar** [comment]
Thanks @milenaveneziani, I thought we'd done this.  I think maybe we could improve things by placing the numbers to the side like e3sm_diags does:
![image](https://user-images.githubusercontent.com/4179064/102594500-959b4900-4116-11eb-8e46-41cbe08419b5.png)
rather than in the panel title.

> what do you mean by 'correlation'? how do you calculate it?

I looked at e3sm_diags and they are using Pearson correlation (via CDAT).  We could get the same by calling the numpy `corrcoeff()` function: https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

**Comment by golaz** [comment]
Yes, Pearson correlation is what we want:

covariance(model, obs) / (std(model) * std(obs))

However, each term needs to be computed as a weighted term to account for the variable grid area. I don't know if xarray would automatically take care of that:

http://xarray.pydata.org/en/stable/generated/xarray.corr.html

**Comment by xylar** [comment]
I don't think xarray will account for that automatically but we've already been doing the same weighting when we compute the mean and RMSE, so that shouldn't be difficult.
