### ISSUE TITLE
Incorrect stats on lat-lon SST plots

### ISSUE THREAD

**Issue by golaz** [MPAS-Dev/MPAS-Analysis#860]
On some (?) lat-lon plots, the stats indicating global mean, rmse appear to be wrong, even though the plots themselves look correct. Here is an example:

https://portal.nersc.gov/cfs/e3sm/golaz/E3SMv2/v2.LR.historical_0111/mpas_analysis/ts_1850-1984_climo_1955-1984/ocean/index.html#global_sst&gid=2&pid=3

The bottom panel shows a mean bias of -4.7 degC, which does not look consistent with the contour plot.

The scripts that generated the plots are on NERSC:

/global/cfs/cdirs/e3sm/golaz/E3SMv2/v2.LR.historical_0111/post/scripts

**Comment by xylar** [comment]
Thanks @golaz!

Could you open up permissions on:
```
/global/cfs/cdirs/e3sm/golaz/E3SMv2/v2.LR.historical_0111/post/analysis/mpas_analysis/ts_1850-1984_climo_1955-1984
```
so I can take a look at the masking of the data in the NetCDF files?  I can generate my own but better yet would be to have a careful look at yours.

**Comment by xylar** [comment]
@golaz, don't worry too much.  I took a look at some simple output I use for tesitng.  I believe the explanation is that land is full of zeros, rather than fill values.  I don't know if this is a change in MPAS-Analysis or ncremap.  I need to figure it out.  But that could certainly account for the bad statistics.

**Comment by xylar** [comment]
@czender, I may need to ask for your thoughts on this shortly. Just pinging you so you see this issue.

**Comment by xylar** [comment]
I believe that `ncremap` is behaving differently when it remaps an MPAS variable without any fill values vs. when there are fill values.  Thus, it correctly masks 3D temperature because bathymetry is masked but just put zeros for land when remapping SST (which has no fill values on the MPAS mesh).

I have a vague memory that I had run into this problem before and I *thought* I have fixed it by supplying a `_FillValue` attribute on variables that need masking even if there aren't actually any fill values in the field.  If my memory is correct, it seems like `ncreamp` has changed its behavior in these circumstances and now fills with zeros even in this case.

I am working on a workaround.  But I am also betting @czender can tell me of a flag or something I am missing to tell `ncremap` that I really, really to want masking in these cases.

Here are some details:
```
$ ncdump -h /global/cscratch1/sd/xylar/analysis_testing/cori-haswell/test_e3sm_unified_1.6.0rc7/main_py3.9/clim/mpas/avg/masked/sst_QU480/mpaso_ANN_000301_000512_climo.nc
ncdump -h ../../masked/sst_QU480/mpaso_ANN_000301_000512_climo.nc | more
netcdf mpaso_ANN_000301_000512_climo {
dimensions:
	Time = UNLIMITED ; // (0 currently)
	nCells = 1791 ;
variables:
	float timeMonthly_avg_activeTracers_temperature(nCells) ;
		timeMonthly_avg_activeTracers_temperature:_FillValue = 9.96921e+36f ;
		timeMonthly_avg_activeTracers_temperature:long_name = "potential temperature" ;
		timeMonthly_avg_activeTracers_temperature:units = "degrees Celsius" ;
		timeMonthly_avg_activeTracers_temperature:cell_methods = "Time: mean" ;
	double validMask(nCells) ;
		validMask:_FillValue = 9.96920996838687e+36 ;
...

$ srun ncremap -m /global/cscratch1/sd/xylar/analysis_testing/cori-haswell/test_e3sm_unified_1.6.0rc7/main_py3.9/mapping/map_QU480_to_0.5x0.5degree_bilinear.nc --vrb=1 -P mpas -C -R "--renormalize=0.01 --rgr lat_nm_out=lat --rgr lon_nm_out=lon" /global/cscratch1/sd/xylar/analysis_testing/cori-haswell/test_e3sm_unified_1.6.0rc7/main_py3.9/clim/mpas/avg/masked/sst_QU480/mpaso_ANN_000301_000512_climo.nc /global/cscratch1/sd/xylar/analysis_testing/cori-haswell/test_e3sm_unified_1.6.0rc7/main_py3.9/clim/mpas/avg/remapped/sst_QU480_to_0.5x0.5degree/mpaso_ANN_000301_000512_climo.nc

$ ncdump -v timeMonthly_avg_activeTracers_temperature /global/cscratch1/sd/xylar/analysis_testing/cori-haswell/test_e3sm_unified_1.6.0rc7/main_py3.9/clim/mpas/avg/remapped/sst_QU480_to_0.5x0.5degree/mpaso_ANN_000301_000512_climo.nc

...
 timeMonthly_avg_activeTracers_temperature =
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
...
```

**Comment by czender** [comment]
Thanks for reproducing @xylar, I'll be able to look at this in a few hours...

**Comment by xylar** [comment]
`chmod`ding now so you'll have access...
