### ISSUE TITLE
Add Southern Ocean isopycnal plot to default output

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/MPAS-Analysis#876]
Zonal averages of isopycnal contours are useful to see the influence of mesoscale eddies (when resolved) and GM eddy parameterization on the meridional tilt of isopycnals.  Please add these to the default plots and webpage.

**Comment by xylar** [comment]
@mark-petersen, are you sure that zonal averages are going to be useful?  What @milenaveneziani and I had discussed were cross sections, some where we could compare with WOCE and some with SOSE.  If we do a zonal average, we're very likely to wash out a lot of detail and it isn't clear to me that there is a useful data set to compare with (though we could try making a WOA18 or SOSE zonal average).

**Comment by milenaveneziani** [comment]
I agree with @xylar. We discussed the following sections: Drake Passage (observations should be available there, from Scripps); WOCE @0deg longitude; and perhaps a couple of SOSE sections where we see the bottom warming (Amery, Ross, and one in EA).

**Comment by milenaveneziani** [comment]
Does anybody remember if the Drake Passage section plots done in the past also included the Scripps observations? Otherwise, we should be able to download them since they are public.

**Comment by xylar** [comment]
No, those sections were just model vs. model.

**Comment by milenaveneziani** [comment]
Unfortunately section observations are always a bit of a pain to process, since there are different cruises done in separate campaigns and often by different institutions. A decade old data set is C-Drake (PI was Teresa Chereskin from Scripps): http://www.cdrake.org/index.html. But a google search also points me to 2021 cruises done by BAS.
Either way, we'd have to process the various cruise lines into a sort of climatological product..

**Comment by xylar** [comment]
@milenaveneziani, do you have time to get ahold of the BAS data? If so, that would be really great. I'll start on the rest today

**Comment by milenaveneziani** [comment]
I can take a look after the AFOS meeting (ends on Wed).

**Comment by xylar** [comment]
@milenaveneziani, it turns out that one of our WOCE transects (A21) covers the Drake Passage already.  So I think we're set.  It's just that we usually plot only a small fraction of the full transect.  I think we need to modify the WOCE plotting to allow us to see both the full transects and the truncated ones close to Antarctica.

**Comment by xylar** [comment]
This was done in #877
