### ISSUE TITLE
MOC is infinite

### ISSUE THREAD

**Issue by darincomeau** [MPAS-Dev/MPAS-Analysis#965]
In running MPAS-Analysis on the SORRM historical run, I've been getting errors with the MOC task. Looking into it, the `mocTimeSeries` files are being created, but

```
 mocAtlantic26 = Infinity, Infinity, Infinity, Infinity, Infinity, Infinity,
    Infinity, Infinity, Infinity, Infinity, Infinity, Infinity, Infinity,
    Infinity, Infinity, Infinity, Infinity, Infinity, Infinity, Infinity,
```

**Comment by darincomeau** [comment]
@xylar I know you're away this week and don't expect you to do anything here, I'm opening this more for me to keep track of (and hope that's ok usage!).

**Comment by xylar** [comment]
It's definitely fine to open this.

I don't believe this is likely to be an MPAS-Analysis issue, I think it's more likely the masking issue fixed in https://github.com/E3SM-Project/E3SM/pull/5458 unless you are sure you're running with that fix.

Can you verify that the 6 fields (vertical velocity tops and normal velocities; no suffix, GM and MLE or whatever it's called) are all finite? An ncdump on each for one set of monthly output and just for s few cells and vertical levels should do.

**Comment by darincomeau** [comment]
Thanks @xylar - indeed seeing infinities there. I must have missed this by going back to the v2.1 tag.
